name: My First Workflow

on: [push, pull_request]
  branches: [main, test]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    stesps:
      - name: Print a greeting
        run: echo "Hello! The workflow worked"