name: My First Workflow

on: 
  push:
  pull_request:
    branches: [main, test]
jobs:
  tset-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.jobs
        uses: actions/setup-node@v4
      
      - name: Install Dependencies
        run: npm ci